### ISSUE TITLE
GitHub invitation to GDCR Shenzhen

### ISSUE THREAD

**Issue by paulvi** [coderetreat-china/coderetreat-china.github.io#3]
@olalonde Olivier 

welcome to come, please register at http://coderetreat-china.github.io/shenzhen

**Comment by olalonde** [comment]
Thanks for the invitation but I don't think I'll be able to participate unfortunately because I don't speak Chinese.

**Comment by paulvi** [comment]
It will be 50/50 , I'll be facilitating in English, there will be 5+ expats, plus check http://coderetreat-china.github.io/survival-Chinese-for-developer

**Comment by paulvi** [comment]
see https://yoopay.cn/event/31126629 for current list

or check http://coderetreat-china.github.io/shenzhen in a week for results
